name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Start Message
        run: echo "Starting the build process..."

      - name: Change to Project Directory
        run: |
          cd $GITHUB_WORKSPACE  # Navigate to the root of the workspace
          cd TestBuildApp        # Navigate to the TestBuildApp directory
          ls -al                 # List contents of the directory for debugging

      - name: Display Current Directory
        run: pwd  # Print the current directory for debugging

      - name: Build Project
        run: dotnet build
