name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: [self-hosted, Windows]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Start Message
        run: echo "Starting the build process..."

      - name: Restore Dependencies
        run: dotnet restore TestBuildApp/TestBuildApp.sln

      - name: Build Project
        run: dotnet build TestBuildApp/TestBuildApp.sln

      - name: Create Publish Directory
        run: mkdir -p ${{ github.workspace }}/publish

      - name: Publish Application
        run: dotnet publish -c Release -r win-x64 --self-contained -o ${{ github.workspace }}/publish TestBuildApp/TestBuildApp.sln
       
      - name: Display Published Artifacts
        run: ls -R ${{ github.workspace }}/publish

      - name: Archive Publish Directory
        uses: actions/upload-artifact@v4
        with: 
          name: publish-artifact
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: self-hosted  # Ensure this is correct for your self-hosted Windows runner

    needs: build

    steps:
      - name: Display Start Message
        run: echo "Starting the deployment process..."

      - name: Download Published Artifacts
        uses: actions/download-artifact@v4
        with:
          name: publish-artifact
          path: ${{ github.workspace }}\publish

      - name: Display Downloaded Artifact Contents
        run: dir /s ${{ github.workspace }}\publish

      - name: Create Deployment Directory
        run: mkdir "C:\Deepak\deployment"

      - name: Display Deployment Directory Contents Before Copy
        run: dir /s "C:\Deepak\deployment"

      - name: Copy to Deployment Location
        run: xcopy /E /I /Y "${{ github.workspace }}\publish\*" "C:\Deepak\deployment\"

      - name: Display Deployment Directory Contents After Copy
        run: dir /s "C:\Deepak\deployment"
