name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Start Message New5
        run: echo "Starting the build process..."

      - name: Print GitHub Actions Workspace Path
        run: echo "GitHub Actions workspace path:" $GITHUB_WORKSPACE

      - name: List Contents
        run: ls -al

      - name: Debug Information
        run: |
          pwd
          ls -al $GITHUB_WORKSPACE

      - name: Change to Project Directory
        run: cd "$GITHUB_WORKSPACE"

      - name: Build Project
        run: dotnet build TestBuildApp.csproj
        working-directory: $GITHUB_WORKSPACE/TestBuildApp
