name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        run: |
          docker run --network host \
          -e SONAR_TOKEN=sqp_00610d8d56af34cb0864023ecbbbebb8e637d5dc \
          sonarsource/sonar-scanner-cli:latest \
          -Dsonar.projectKey=test_repoaq1sw2de \
          -Dsonar.host.url=http://192.168.0.2:9000

