name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Add Sonar Scanner path to $GITHUB_PATH
      - name: Set up Sonar Scanner path
        run: echo "C:\sonar-scanner\bin" >> $GITHUB_PATH

      # Verify Sonar Scanner path
      - name: Verify Sonar Scanner path
        run: sonar-scanner -h
