name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Start Message
        run: echo "Starting the build process..."

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: List Workspace Contents
        run: ls -al "${{ github.workspace }}"

      - name: Change to Project Directory
        run: cd "${{ github.workspace }}"

      - name: List Project Directory Contents
        run: ls -al TestBuildApp

      - name: Build Project
        run: dotnet build TestBuildApp/TestBuildApp.csproj
