name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Use the defined path in the subsequent steps
      - name: Run SonarQube analysis
        run: |
          sonar-scanner -Dsonar.login=sqp_b1b9028638217f797048a9570753e3a125591c51 -Dsonar.projectKey=test_repoaq1sw2de
