name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Start Message New15
        run: echo "Starting the build process..."

      - name: Display Current Directory
        run: pwd

      - name: Change to Project Directory
        run: cd TestBuildApp

      - name: Build Project
        run: dotnet build
