name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up environment
      run: |
        # Use PowerShell to access environment variables
        echo "Path: $env:PATH"
        echo "GitHub Token: $env:SONAR_HOST_URL"

    - name: Set up environment
      run: |
        # Use PowerShell to access environment variables
        echo "Path: $env:PATH"
        echo "Sonar Scanner Path: $env:Sonar_Scanner_Path"
        echo "Sonar Host URL: $env:SONAR_HOST_URL"

