name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Start Message New20
        run: echo "Starting the build process..."

      - name: Change to Project Directory
        run:  |
            cd $GITHUB_WORKSPACE
            cd TestBuildApp
            pwd  # Print the current directory for debugging purposes
             
      - name: Build Project
        run: dotnet build TestBuildApp.csproj
