name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up environment
      run: |
        # Check if PowerShell is available
        if [ -x "$(command -v powershell)" ]; then
          # Use PowerShell to access environment variables
          powershell -Command "Get-ChildItem Env: | ForEach-Object { Write-Host "$($_.Name): $($_.Value)" }"
        else
          # Fallback to Git Bash
          echo "Path: $PATH"
          echo "Sonar Host URL: $SONAR_HOST_URL"
        fi
