name: SonarQube CI

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Cache SonarQube packages
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar
        restore-keys: ${{ runner.os }}-sonar

    - name: Install SonarQube scanner
      run: |
        curl -L -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-windows.zip
        unzip sonar-scanner.zip -d sonar-scanner
        echo "SonarScanner installed successfully."

    - name: Build and analyze with SonarScanner
      run: |
        sonar-scanner/sonar-scanner-5.0.1.3006-windows/bin/sonar-scanner \
          -Dsonar.projectKey=test_repoaq1sw2de \
          -Dsonar.host.url=http://192.168.16.26:9099 \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
