name: Test WinRM Remote Connection

on:
  push:
    branches:
      - main  # Run the workflow when pushing to the main branch
  workflow_dispatch:  # Allows manual execution from GitHub UI

jobs:
  remote-winrm:
    runs-on: windows-latest  # Use Windows runner

    steps:
      - name: Install WinRM Module
        shell: pwsh
        run: Install-Module -Name PSWSMan -Force -SkipPublisherCheck -Scope CurrentUser

      - name: Test Remote WinRM Connection
        shell: pwsh
        run: |
          $secPassword = ConvertTo-SecureString 'P@ssw0rd' -AsPlainText -Force
          $cred = New-Object System.Management.Automation.PSCredential ('EDGEAPPBK\hhadmin', $secPassword)
          
          Invoke-Command -ComputerName edgeappbk -Credential $cred -ScriptBlock { 
            hostname
          }
