name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Start Message new11
        run: echo "Starting the build process..."

      - name: Change to Project Directory
        run:  |
             cd $GITHUB_WORKSPACE/$(find . -type d -iname 'TestBuildApp' -print -quit)
             pwd  # Print the current directory for debugging purposes
             
      - name: Build Project
        run: dotnet build TestBuildApp.csproj
