name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Start Message
        run: echo "Starting the build process..."

      - name: Display GitHub Actions Workspace
        run: echo "GitHub Actions workspace path: $GITHUB_WORKSPACE"

      - name: List Contents
        run: ls -al

      - name: Change to Project Directory
        run: cd "$GITHUB_WORKSPACE" && cd $(find . -type d -name 'TestBuildApp' -print -quit)

      - name: Display Current Directory
        run: pwd

      - name: Build Project
        run: dotnet build
