name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Start Message
        run: echo "Starting the build process..."

      - name: Change to Project Directory
        run:  cd "/c/Deepak/Test/test_repo/TestBuildApp"

      - name: Build Project
        run: dotnet build TestBuildApp.csproj
