name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  sonarqube-analysis:
    runs-on: windows-latest  # Running on Windows since SonarQube scanner is on Windows 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'

      - name: SonarQube Scan
        run: |
          sonar-scanner.bat \
            -Dsonar.projectKey=test_repoaq1sw2de \
            -Dsonar.host.url=http://localhost:9000 \
            -Dsonar.login=sqp_b1b9028638217f797048a9570753e3a125591c51
