name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonarqube:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Set up SonarQube Scanner
        uses: sonarsource/sonarqube-scan-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-project-key: ${{ secrets.SONAR_PROJECT_KEY }}
          sonar-project-name: ${{ secrets.SONAR_PROJECT_NAME }}
          sonar-host-url: ${{ secrets.SONAR_HOST_URL }}
