name: Sonar Scan

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Execute SonarScanner
      run: |
        .\sonar-scanner.bat "-Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}" "-Dsonar.sources=src" "-Dsonar.host.url=http://192.168.16.26:9099" "-Dsonar.login=sqp_75a485ca7f0854c5b0aa32243614bca5a666558e"
