name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up environment variables or paths
      - name: Set up environment
        run: |
          echo "PATH_TO_SONAR_SCANNER=c:/sonar-scanner/bin" >> $GITHUB_ENV

      # Use the defined path in the subsequent steps
      - name: Run SonarQube analysis
        run: |
          export PATH="$PATH_TO_SONAR_SCANNER:$PATH"
          /c/sonar-scanner/bin/sonar-scanner.bat -Dsonar.projectKey=test_repoaq1sw2de -Dsonar.host.url=http://localhost:9000 -Dsonar.token=sqp_b1b9028638217f797048a9570753e3a125591c51
