name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Start Message
        run: echo "Starting the build process..."

      - name: Build Project 1
        run: dotnet build C:\Deepak\Test\test_repo\test_repo\test_repo\TestBuildApp\TestBuildApp.csproj

      - name: Build Project 2
        run: dotnet build
