name: EdgePlus CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Start Message
        run: echo "Starting the build process..."

      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: sonar-scanner -Dsonar.host.url=http://192.168.16.26:9099 -Dsonar.login=$SONAR_TOKEN

      - name: Change to Project Directory
        run: cd "${{ github.workspace }}"

      - name: Restore Dependencies
        run: dotnet restore TestBuildApp/TestBuildApp.sln

      - name: Build Project
        run: dotnet build TestBuildApp/TestBuildApp.sln
