name: CI/CD with SonarQube

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: SonarQube Scan
        run: |
          sonar-scanner \
            -Dsonar.host.url=http://192.168.16.26:9099 \
            -Dsonar.login=${{ secrets.SONARQUBE_TOKEN }}
        env:
          SONARQUBE_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
