name: Check SonarQube Connection

on:
  workflow_dispatch:  # Trigger the workflow manually

jobs:
  check-sonarqube-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Check Connection
        run: |
          response=$(curl -s -o /dev/null -w "%{http_code}" "${{ secrets.SONAR_HOST_URL }}/api/server/version")
          if [ $response -eq 200 ]; then
            echo "SonarQube server is up and running."
          else
            echo "Failed to connect to SonarQube server. HTTP Status code: $response"
            exit 1
          fi
