name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Start Message
        run: echo "Starting the build process..."

      - name: Restore Dependencies
        run: dotnet restore TestBuildApp/TestBuildApp.sln --verbosity detailed

      - name: Build Project
        run: dotnet build TestBuildApp/TestBuildApp.sln --verbosity detailed

      - name: Create Publish Directory
        run: mkdir -p ${{ github.workspace }}/publish

      - name: Publish Application
        run: dotnet publish TestBuildApp/TestBuildApp.sln -c Release -r win-x64 --self-contained -o ${{ github.workspace }}/publish --verbosity detailed
       
      - name: Display Published Artifacts
        run: ls -R ${{ github.workspace }}/publish

      - name: Archive Publish Directory
        uses: actions/upload-artifact@v4
        with: 
          name: publish-artifact
          path: ${{ github.workspace }}/publish

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Start Message
        run: echo "Starting the deployment process..."

      - name: Download Published Artifacts
        uses: actions/download-artifact@v4
        with:
           name: publish-artifact
           path: ${{ github.workspace }}/publish

      - name: Display Downloaded Artifact Contents
        run: ls -R ${{ github.workspace }}/publish

      - name: Create Deployment Directory
        run: mkdir -p "/home/runner/deployment"

      - name: Copy to Deployment Location
        run: cp -r ${{ github.workspace }}/publish/* "/home/runner/deployment/"

      - name: Display Deployment Directory Contents
        run: ls -R "/home/runner/deployment"
