name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Start Message test
        run: echo "Starting the build process..."

      - name: Build Project
        shell: bash
        run: |
          cd /c/Deepak/Test/test_repo/TestBuildApp
          dotnet build TestBuildApp.csproj
