name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v2  

      - name: Install dotnet version tool
        run: dotnet tool install -g dotnet-version-cli

      - name: Set Version
        run: dotnet version --project Qor3.sln --auto-increment

      - name: Display Start Message
        run: echo "Starting the build process..."

      - name: Change to Project Directory
        run: cd "${{ github.workspace }}"

      - name: Restore Dependencies
        run: dotnet restore TestBuildApp/TestBuildApp.sln

      - name: Build Project
        run: dotnet build TestBuildApp/TestBuildApp.sln
