name: SonarQube Analysis

on:
  push:
    branches:
      - main  # Adjust branch name as needed

jobs:
  sonarqube-analysis:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SonarQube Scanner
        uses: sonarsource/setup-sonarqube@v1
        with:
          sonarqube-version: '8.x'
          server-url: ${{ secrets.SONAR_HOST_URL }}
          token: ${{ secrets.SONAR_TOKEN }}

      - name: Run SonarQube analysis
        env:
          SONAR_PROJECT_KEY: test_repoaq1sw2de
        run: |
          sonar-scanner \
            -Dsonar.projectKey=$SONAR_PROJECT_KEY \
            -Dsonar.host.url=$SONAR_HOST_URL \
            -Dsonar.token=$SONAR_TOKEN
