name: SonarQube Connectivity Test

on:
  push:
    branches:
      - main

jobs:
  connectivity-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Test SonarQube Connectivity
      run: |
        # Define the SonarQube server URL and port
        SONARQUBE_SERVER="http://192.168.89.241:9000"
        # Define your SonarQube token
        SONARQUBE_TOKEN="${{ secrets.SONARQUBE_TOKEN }}"

        # Test connectivity using curl with token
        echo "Testing connectivity to SonarQube server at: $SONARQUBE_SERVER with token"
        curl --head --fail --silent --show-error -H "Authorization: Bearer $SONARQUBE_TOKEN" "$SONARQUBE_SERVER"

        # Check the exit status of curl command
        if [ $? -eq 0 ]; then
            echo "Connectivity test successful. SonarQube server is reachable with token."
        else
            echo "Connectivity test failed. SonarQube server is not reachable with token."
            exit 1
        fi
