name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Display Start Message New24
        run: echo "Starting the build process..."

      - name: Change to Project Directory
        run: cd "$GITHUB_WORKSPACE/$(find . -type d -name 'TestBuildApp' -print -quit)"

      - name: Display Current Directory
        run: pwd

      - name: Build Project
        run: dotnet build "C:/Deepak/Test/test_repo/TestBuildApp/TestBuildApp.csproj"
