name: Check Secrets

on:
  push:
    branches:
      - main

jobs:
  check-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secrets
        run: |
          echo "SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}"
          echo "SONAR_PROJECT_NAME: ${{ secrets.SONAR_PROJECT_NAME }}"
          echo "SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}"
          echo "SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}"
