name: CI/CD Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Display Start Message
        run: echo "Starting the build process..."

      - name: Change to Project Directory
        run: cd "${{ github.workspace }}"

      - name: Restore Dependencies
        run: dotnet restore TestBuildApp.sln

      - name: Build Project
        run: dotnet build TestBuildApp.sln
