name: My Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Check out code
      uses: actions/checkout@v2
      
    - name: Set up environment
      run: |
        if [ -x "$(command -v powershell)" ]; then
          # Use PowerShell to access environment variables
          powershell -Command "Get-ChildItem Env: | ForEach-Object { Write-Host "$($_.Name): $($_.Value)" }"
        else
          echo "PowerShell is not available, falling back to Git Bash"
          # Use Bash commands to access environment variables
          echo "Path: $PATH"
          echo "Sonar Host URL: $SONAR_HOST_URL"
          echo "Sonar Path: $SONAR_SCANNER_PATH"
        fi

    - name: Run SonarScanner
      run: |
        if [ -x "$(command -v powershell)" ]; then
          sonar-scanner -Dsonar.projectKey=test_repoaq1sw2de -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
        else
          $SONAR_SCANNER_PATH/sonar-scanner -Dsonar.projectKey=test_repoaq1sw2de -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_TOKEN
        fi
      env:
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        SONAR_SCANNER_PATH: ${{ secrets.SONAR_SCANNER_PATH }}
