name: Display Text File Content

on:
  push:
    branches:
      - main

jobs:
  display_content:
    runs-on: windows-latest

    steps:
      - name: Read and display text file content
        run: |
          Get-Content "C:\Users\Deepak Mangal\Documents\1.txt"
