name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SonarQube Scan
        run: |
          docker run --network host \
          -e SONAR_TOKEN=sqb_95895eaa1f55d55b1b37a31ea09c59494a7d8c30 \
          sonarsource/sonar-scanner-cli:latest \
          -Dsonar.projectKey=test_repoaq1sw2de \
          -Dsonar.host.url=http://192.168.16.26:9099

